name: Build and publish a Docker image to ghcr.io
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: almalinux_rpmfusion
          tags: latest
          registry: ghcr.io
          dockerfile: almalinux_rpmfusion/Dockerfile
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
